plugins {
  alias(libs.plugins.fabric.loom)
}

loom {
  accessWidenerPath = file("src/main/resources/ironcore.accesswidener")
}

version = project.ironcore_version
group = project.ironcore_maven_group

base {
  archivesName = "ironcore-common"
}

dependencies {
  minecraft libs.minecraft
  implementation libs.gson
  testImplementation libs.junit.jupiter
  testRuntimeOnly libs.junit.platform.launcher
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}
