modLoader = "javafml"
loaderVersion = "[1,)"
license = "gpl-3.0"

[[mods]]
modId = "ironchest"
version = "${ironchest_version}"
displayName = "Iron Chests"
authors = "anner, gathertocraft"
displayURL = "https://www.gathertocraft.com"
description = "Bigger Chests for Minecraft"

[[dependencies.ironchest]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0.52-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ironchest]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,26.4)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ironchest]]
modId = "ironcore"
type = "required"
versionRange = "[${ironcore_version},)"
ordering = "AFTER"
side = "BOTH"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "ironchest.mixins.json"
