plugins {
  alias(libs.plugins.fabric.loom)
}

loom {
  accessWidenerPath = file("src/main/resources/ironchest.accesswidener")
}

version = project.ironchest_version
group = project.maven_group

base {
  archivesName = "ironchests-common"
}

dependencies {
  minecraft libs.minecraft

  implementation(project(":iron-core:common"))
}
